name: Build

on:
  pull_request:
    branches: [master]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout plugin repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Run unit tests
        run: |
          pwd
          ls -ltar
          npm ci
          npm run test

  quality-gate:
    needs: unit-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout plugin repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install and Run Quality Gates CLI
        run: |
          node -v
          npm -v
          # Clone the quality-gates-platform repo
          git clone https://github.com/rbraju/quality-gates-platform.git
          cd quality-gates-platform
          # Install dependencies and build
          npm ci
          npm run build

          # Link CLI & Run
          npm link
          qgate $GITHUB_WORKSPACE/src
