name: Quality Gate

on:
  push:
    branches: [master]

jobs:
  quality-gate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout plugin repo
        uses: actions/checkout@v4

      - name: List files
        run: ls -la

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      
      - run: node -v
      - run: npm -v

      - name: Install and Run Quality Gates CLI
        run: |
          # Clone the quality-gates repo
          git clone https://github.com/rbraju/quality-gates-platform.git
          cd quality-gates-platform

          # Install dependencies and build
          npm ci
          npm run build

          # Link CLI & Run
          npm link
          qgate $GITHUB_WORKSPACE/src

      - name: Run unit tests
        run: |
          npm ci
          npm run tests
