name: Quality Gate

on:
  push:
    branches: [master]

jobs:
  quality-gate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout plugin repo
        run: actions/checkout@v4

      - name: List files
        run: ls -la

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: node -v
      - run: npm -v

      - name: Clone Quality Gates Platform
        run: |
          git clone https://github.com/rbraju/quality-gates-platform.git
          cd quality-gates-platform
          npm ci
          npm build || true
          npm link

      - name: Run Quality Gate
        run: qgate ./src
